name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ldid
        run: |
          brew install ldid

      - name: Build and Package IPA
        run: |
          cd TrollApps
          chmod +x build.command
          ./build.command

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrollApps-IPA
          path: |
            TrollApps/build/TrollApps.ipa
            TrollApps/build/TrollApps.tipa
